#!/usr/bin/perl
#CODED BY G66K
#Retrieve Real IP behind cloudflare
use WWW::Mechanize;
use strict;
use warnings;
use v5.010;


if($#ARGV != 0){
  say("Usage: $0 domain.com");
  say("E.g $0 hizb-ut-tahrir.info");
  exit(0);
}
my $domain = $ARGV[0];
chomp($domain);
say("Catching Real IP For : ". $domain);

my $url = 'http://www.crimeflare.com/cfs.html';
my $m = WWW::Mechanize->new(autocheck => 0);
$m->get($url);
$m->field('cfS', $domain);
my $response = $m->submit();
my $allo = $response->content();
my @dns =  ($allo =~ /(?:<BR>([a-z0-9]+.?[a-z0-9]+.?[a-z0-9]+.?[a-z]{3,}))/g);
my @info = ($allo =~ /<BR><BR>([a-zA-Z].+:)<UL>\s<LI>([0-9]+-[0-9]+-[0-9]+:\s\S+\s+[0-9]+.[0-9]+.[0-9]+.[0-9]+\s\S*\s\S+)\s<LI>([0-9]+-[0-9]+-[0-9]+:\s\S+\s+[0-9]+.[0-9]+.[0-9]+.[0-9]+\s\S*\s\S+)\s<LI>([0-9]+-[0-9]+-[0-9]+:\s\S+\s+[0-9]+.[0-9]+.[0-9]+.[0-9]+\s\S*\s\S+)/);
 

say("CloudFlareDns: ".$dns[0]) if defined($dns[0]);
say("CloudFlareDns: ".$dns[1]) if defined($dns[1]);
say("------------------------");
say($info[0]) if defined($info[0]);
say($info[1]) if defined($info[1]);
say($info[2]) if defined($info[2]);
say($info[3]) if defined($info[3]);


