#!/usr/bin/perl
#CODED BY G66K
#Retrieve Real IP behind cloudflare
use WWW::Mechanize;
use strict;
use warnings;
use v5.010;


if($#ARGV != 0){
  say("Usage: $0 domain.com");
  exit(0);
}

my $domain = $ARGV[0];
chomp($domain);

say("Catching Real IP For : ". $domain);

my $url = 'http://www.crimeflare.com/cfs.html';
	my $m = WWW::Mechanize->new(autocheck => 0);
	   $m->agent('Mozilla/5.0 (Windows; U; Windows NT 6.1; nl; rv:1.9.2.13) Gecko/20101203 Firefox/3.6.13');
	   $m->get($url);
		$m->field('cfS', $domain);	
	my $response = $m->submit();
	my $allo = $response->content();
	my @dns =  ($allo =~ /(?:<BR>([a-z0-9]+.?[a-z0-9]+.?[a-z0-9]+.?[a-z]{3,}))/g);
	my @info = ($allo =~ /([0-9]{4}-[0-9]{2}-[0-9]{2}:\s(?:.+))/g);

		say("CloudFlareDns: ".$dns[0]) if defined($dns[0]);
		say("CloudFlareDns: ".$dns[1]) if defined($dns[1]);
if(@info){
	say("------------------------");
	foreach my $info (@info){
			say $info if defined $info;
}


}else{
	say("No direct-connect IP address was found for this domain.");
}
